baseURL = "https://USERNAME.github.io/"   # 임시 URL, 나중에 Custom Domain으로 교체
title = "My Tech Blog"
theme = "PaperMod"
publishDir = "public"
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = true
